services:
  postgres:
    image: postgres:15.3
    container_name: demand-lever-postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432" # Exposing port to the host machine
